[
    {
        "task_id": 1,
        "id": "cohort_1",
        "title": "Cohort 1",
        "start_date": "2023-01-01T06:00:00.000Z",
        "end_date": "2023-11-01T05:00:00.000Z",
        "hubspot_ticket": null,
        "instructor": null,
        "teacher_assistant": null,
        "mode": null,
        "course_link": null,
        "rocketchat": null,
        "location": null,
        "day_of_week": null,
        "active_status": null,
        "student_number_start": null,
        "student_number_end": null,
        "parent": null
    },
    {
        "task_id": 2,
        "id": "cohort_2",
        "title": "Cohort 2",
        "start_date": "2023-11-01T05:00:00.000Z",
        "end_date": "2024-04-01T05:00:00.000Z",
        "hubspot_ticket": null,
        "instructor": null,
        "teacher_assistant": null,
        "mode": null,
        "course_link": null,
        "rocketchat": null,
        "location": null,
        "day_of_week": null,
        "active_status": null,
        "student_number_start": null,
        "student_number_end": null,
        "parent": null
    },
    {
        "task_id": 3,
        "id": "course_1",
        "title": "Web 101",
        "start_date": "2023-01-01T06:00:00.000Z",
        "end_date": "2023-02-01T06:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Matthew Huntsberry",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "MW",
        "active_status": 1,
        "student_number_start": 20,
        "student_number_end": 18,
        "parent": "cohort_1"
    },
    {
        "task_id": 4,
        "id": "course_2",
        "title": "JS 211",
        "start_date": "2023-02-01T06:00:00.000Z",
        "end_date": "2023-03-01T06:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Matthew Huntsberry",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "MW",
        "active_status": 1,
        "student_number_start": 18,
        "student_number_end": 18,
        "parent": "cohort_1"
    },
    {
        "task_id": 5,
        "id": "course_3",
        "title": "JS 311",
        "start_date": "2023-03-01T06:00:00.000Z",
        "end_date": "2023-04-01T05:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Matthew Huntsberry",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 18,
        "student_number_end": 17,
        "parent": "cohort_1"
    },
    {
        "task_id": 6,
        "id": "course_4",
        "title": "JS 411",
        "start_date": "2023-04-01T05:00:00.000Z",
        "end_date": "2023-05-01T05:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Matthew Huntsberry",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 17,
        "student_number_end": 17,
        "parent": "cohort_1"
    },
    {
        "task_id": 7,
        "id": "course_5",
        "title": "JOB 401",
        "start_date": "2023-05-01T05:00:00.000Z",
        "end_date": "2023-06-01T05:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Matthew Huntsberry",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 17,
        "student_number_end": 17,
        "parent": "cohort_1"
    },
    {
        "task_id": 8,
        "id": "course_1",
        "title": "WEB 101",
        "start_date": "2023-11-01T05:00:00.000Z",
        "end_date": "2023-12-01T06:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Juan Rodriguez",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 20,
        "student_number_end": 20,
        "parent": "cohort_2"
    },
    {
        "task_id": 9,
        "id": "course_2",
        "title": "JS 211",
        "start_date": "2023-12-01T06:00:00.000Z",
        "end_date": "2024-01-01T06:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Yousef Seedholm",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 20,
        "student_number_end": 20,
        "parent": "cohort_2"
    },
    {
        "task_id": 10,
        "id": "course_3",
        "title": "JS 311",
        "start_date": "2023-01-01T06:00:00.000Z",
        "end_date": "2024-02-01T06:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Westin Sewell",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 20,
        "student_number_end": 20,
        "parent": "cohort_2"
    },
    {
        "task_id": 11,
        "id": "course_4",
        "title": "JS 411",
        "start_date": "2023-02-01T06:00:00.000Z",
        "end_date": "2024-03-01T06:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Matthew Huntsberry",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 20,
        "student_number_end": 19,
        "parent": "cohort_2"
    },
    {
        "task_id": 12,
        "id": "course_5",
        "title": "JOB 501",
        "start_date": "2023-03-01T06:00:00.000Z",
        "end_date": "2024-04-01T05:00:00.000Z",
        "hubspot_ticket": "fake hubspot ticket",
        "instructor": "Matthew Huntsberry",
        "teacher_assistant": "John Smith",
        "mode": "Online",
        "course_link": "fake course link",
        "rocketchat": "fake rocket chat",
        "location": "Austin",
        "day_of_week": "T-TH",
        "active_status": 1,
        "student_number_start": 19,
        "student_number_end": 19,
        "parent": "cohort_2"
    }
]